-- select * from employee
-- #1
-- select * from employee where city in ('Calgary')
-- #2
-- select max (birth_date) from employee
-- #3
-- select min (birth_date) from employee
-- #4
-- select * from employee where reports_to =2;
-- #5
-- Select Count(*) FROM employee WHERE city = 'Lethbridge'